### ISSUE TITLE
'Feeling stupid' problems

### ISSUE THREAD

**Issue by nickbe** [getgrav/grav-plugin-featherlight#1]
According to the original featherlicht documentation the folloing gallery.html.twig template should work, although it doesn't here. And no matter what i do I can't nail the problem...

```
<div class="modular-row {{ page.header.class}}">

    <div style="text-align:center;">
        <h2>{{page.header.title}}</h2>
    </div>

    <div style="text-align:center; width: 100%; margin-left: auto; margin-right: auto; padding-bottom: 30px;">
        {% for image in page.media.images|sort %}
            <a href="{{ image.url }}" data-featherlight="image" style="display:inline-block;
                padding-left: 12px;
                padding-right: 12px;
                padding-top: 12px;
                margin-top: 16px;
                margin-left:5px;
                margin-right:5px;
                background-color: #efefef">{{ image.cropZoom(250,180).html }}</a>
        {% endfor %}
    </div>

    <div style="text-align:center;">
        {{content}}
    </div>

</div>

```

gallery.md looks like this:

```

---
title: This is my gallery
menu: Gallery
featherlight:
        active: true
        openSpeed: 4000
        closeSpeed: 100
        closeOnEsc: true

---
This is my gallery

```
